In [107]:
# Numeric Python-NumPy (used for math)

In [108]:
import numpy as np

In [109]:
a=[2,4,6,8]
b=[1,2,3,4]
c=a+b
c

[2, 4, 6, 8, 1, 2, 3, 4]

In [110]:
type(a)

list

In [111]:
a_array=np.array(a)
a_array #without print shows type array(list/elements) print prints array elements

array([2, 4, 6, 8])

In [112]:
print(a_array)

[2 4 6 8]


In [113]:
b

[1, 2, 3, 4]

In [114]:
c=a_array+b
c

array([ 3,  6,  9, 12])

In [115]:
b_array=np.array(b)
c_array=a_array+b_array
c_array

array([ 3,  6,  9, 12])

In [116]:
c_array.shape

(4,)

In [117]:
multi_d=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [118]:
multi_c=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [119]:
add_array=multi_c+multi_d
add_array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [120]:
zero_1d=np.zeros(6, dtype=int)
zero_1d

array([0, 0, 0, 0, 0, 0])

In [121]:
one_1d=np.ones(6, dtype=int)
one_1d

array([1, 1, 1, 1, 1, 1])

In [122]:
zero_2d=np.zeros((5,6), dtype=int)
zero_2d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [123]:
ones_2d=np.ones((5,6), dtype=int)
ones_2d

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## Arange

In [124]:
# array range like range(start,stop, step) in python

In [125]:
numbers=np.arange(1,61) #output is 1d array
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [126]:
# for loop in np without arange function
# for this convert to list 
data=[]
for i in range(1,11):
    data.append(i)
data=np.array(data)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Reshape and ravel

In [ ]:
'''
Reshape-> Change any dimension of array to any other dimesnsion
Ravel-> Change any dimension array to 1d array/ flatten in ml or scikit learn

'''

'\nReshape-> Change any dimension of array to any other dimesnsion\nRavel-> Change any dimension array to 1d array\n\n'

In [128]:
reshape_numbers=numbers.reshape(10,6)
reshape_numbers

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [129]:
ravel_numbers=np.ravel(reshape_numbers)
ravel_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

### Slicing

In [130]:
ravel_numbers[2]

3

In [131]:
ravel_numbers[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [133]:
print(reshape_numbers[1:3, 1:3])

[[ 8  9]
 [14 15]]


In [134]:
# to extrat only one col of any index
reshape_numbers[:,1]

array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56])

In [135]:
products=np.array(['Mobile','TV','Bottle','Desktop'])
products

array(['Mobile', 'TV', 'Bottle', 'Desktop'], dtype='<U7')

In [137]:
name=np.array(['Bob','Ram','Hari'])
name

array(['Bob', 'Ram', 'Hari'], dtype='<U4')

## Boolean indexing

In [139]:
filter_numbers=numbers<20
numbers[filter_numbers]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [140]:
numbers[numbers<20]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Array Broadcasting

In [ ]:
'''
Rules of array broadcasting
--------------------------------------------------------------
1. All shape of array must be equal.
2. Either one shape row/col must be 1 and other must be equal.
3. One array must be of shape 1,1
'''

In [142]:
arr1=multi_d
arr2=np.array([
    [4,5,6],
    [1,2,3],
    [7,8,9]
])